---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all:!localhost
  remote_user: '{{ remote_user }}'
  become: yes
  become_method: sudo
  vars_files:
    - "vars/{{ deploy_method }}.yml"
    - "vars/resources.yml"
  roles:
    - { role: ansiblebit.oracle-java,
      oracle_java_set_as_default: yes,
      oracle_java_version: 8,
      oracle_java_version_update: 161,
      oracle_java_version_build: 12,
      oracle_java_rpm_filename: jdk-8u161-linux-x64.rpm
      oracle_java_rpm_url: "http://download.oracle.com/otn-pub/java/jdk/{{ oracle_java_version }}u{{ oracle_java_version_update }}-b{{ oracle_java_version_build }}/2f38c3b165be4555a1fa6e98c45e0808/{{ oracle_java_rpm_filename }}"}
    - common
    - hadoop-common
    - hive
    - spark
#    - maven
#    - hive-testbench
