---
# This playbook installs and configures Apache Kafka

- file:
    path: /hadoop/kafka
    state: directory
    mode: 0755

- unarchive:
    src: "{{ tarball_prefix }}/kafka_2.10-0.10.2.1.tgz"
    dest: /hadoop/kafka
    remote_src: True
    extra_opts: "--strip-components=1"
    creates: /hadoop/kafka/LICENSE
