---
# This playbook installs and configures Apache Spark

- file:
    path: /hadoop/spark
    state: directory
    mode: 0755

- unarchive:
    src: "{{ tarball_prefix }}/{{ spark_tarball }}"
    dest: /hadoop/spark
    remote_src: True
    extra_opts: "--strip-components=1"
    creates: /hadoop/spark/LICENSE

- name: Configure spark
  template: src=spark-default.j2 dest=/hadoop/spark/conf/spark-default.xml
  tags: spark

- name: Configure profile
  template: src=profile.j2 dest=/etc/profile.d/spark.sh
  tags: spark

- name: Configure Spark environment file
  template: src=spark-env.j2 dest=/hadoop/spark/conf/spark-env.sh mode=0755
  tags: spark

- name: Configure hive-site file
  template: src=hive-site.j2 dest=/hadoop/spark/conf/hive-site.xml
  tags: spark
  when:
  - master_group in group_names

- name: Link Spark libraries to Hive
  file: src=/hadoop/spark/jars/{{ item }} dest=/hadoop/hive/lib/{{ item }} state=link
  with_items:
  - scala-library-2.11.8.jar
  - spark-core_2.11-2.2.0.jar
  - spark-network-common_2.11-2.2.0.jar
  when:
  - master_group in group_names
